import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.io.File;
import java.io.IOException;

import javax.sound.sampled.*;




// So many bugs here :(
//FIXED AS OF April 7, 8:30 AM
// What changed: Button functions moved to setupWindow from paintComponent
//Removed duplicate ActionListener
//Fixed broken if else statements in ActionPerformed

public class game extends JPanel implements ActionListener, MouseListener {

	public static Object game;
	private JFrame f;
	Dimension screenSize;

	private int width;
	private int height;

	private ImageIcon gameTitle_icon;
	private ImageIcon gameDirections_icon;
	private ImageIcon gameQs_icon;
	private ImageIcon gameOver_icon;
	private ImageIcon ragequit_icon;

	private Image gameTitle;
	private Image gameDirections;
	private Image gameQs;
	private Image gameOver;
	private Image ragequit;
	
	private Clip rageaudio;
	private File rageaudioLocation;
	private AudioInputStream audioInputStream;

	
	private boolean ragequitDTC;

	private int screen;

	private JButton startButton;

	private questions gameQuestions;

	private JButton btn_choice1;
	private JButton btn_choice2;
	private JButton btn_choice3;
	private JButton btn_choice4;
	private JButton playAgain;

	private int points;
	private int mistakes;

	private String[] answerChoices;
	private String thequestion;

	private boolean paintedButtons = false;

	private String choice1;
	private String choice2;
	private String choice3;
	private String choice4;

	private JLabel pointsDisplay;

	public Timer maximumTime;

	public game() {

		gameQuestions = new questions();

		thequestion = gameQuestions.generateQuestion();

		answerChoices = gameQuestions.returnPossibleAnswers();

		maximumTime = new Timer(5000, this);

		points = 0;
		mistakes = 0;
		screen = 0;
		addMouseListener(this);

		gameQs_icon = new ImageIcon("src/images/game question template.png");
		gameTitle_icon = new ImageIcon("src/images/game title.png");
		gameDirections_icon = new ImageIcon("src/images/game directions.png");
		gameOver_icon = new ImageIcon("src/images/game over.png");
		ragequit_icon = new ImageIcon("src/images/ragequit.png");
		

		gameTitle = gameTitle_icon.getImage();
		gameDirections = gameDirections_icon.getImage();
		gameQs = gameQs_icon.getImage();
		gameOver = gameOver_icon.getImage();
		ragequit = ragequit_icon.getImage();
		
		rageaudioLocation = new File("src/sound/ragequit.wav");
		try {
			audioInputStream = AudioSystem.getAudioInputStream(rageaudioLocation);
		} catch (UnsupportedAudioFileException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		try {
			rageaudio = AudioSystem.getClip();
		} catch (LineUnavailableException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
        try {
			rageaudio.open(audioInputStream);
		} catch (LineUnavailableException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        
        rageaudio.stop();
		

		startButton = new JButton();
		startButton.setOpaque(false);
		startButton.setFocusPainted(false);
		startButton.setContentAreaFilled(false);
		// method to remove border from button found @
		// https://forums.oracle.com/ords/apexds/post/removing-the-jbutton-press-effect-3292
		startButton.setBorderPainted(false);
		startButton.addActionListener(this);
		startButton.setBounds(386, 205, 250, 100);
		startButton.setVisible(true);
		System.out.println(startButton.getX());
		add(startButton);

		width = 1024;
		height = 576;

		// System.out.println(width);
		// System.out.println(height);

	}

	public void actionPerformed(ActionEvent e) {
		if (e.getSource() == startButton && screen == 0) {
			screen = 1;
			repaint();
			startButton.setBounds(320, 300, 320, 100);
		}

		else if (e.getSource() == startButton && screen == 1) {
			screen = 2;
			repaint();
			maximumTime.start();

		}

		else if (screen == 2 && e.getSource() == btn_choice1 || e.getSource() == btn_choice2
				|| e.getSource() == btn_choice3 || e.getSource() == btn_choice4) {

			System.out.println("click detected on button (line 122.");

			// System.out.println(gameQuestions.che2ckAnswer(((JButton)
			// e.getSource()).getText(), thequestion));

			if (gameQuestions.checkAnswer((((JButton) (e.getSource())).getText()), thequestion)) {

				System.out.println("point awarded");
				points++;
				System.out.println(((JButton) (e.getSource())).getText());
				/*
				 * try { Thread.sleep(500); // Simply to prevent accidental clicking of a button
				 * in next question, try/catch block autogenerated } catch (InterruptedException
				 * e1) { // TODO Auto-generated catch block e1.printStackTrace(); }
				 * 
				 */
				maximumTime.setDelay(maximumTime.getDelay() - 100);
				maximumTime.restart();

				triggerNext();

				if (mistakes > 4) {
					System.out.println("haha noob you failed!");
					rageaudio.start();
					screen = 3;

				}

			}

			else if (!gameQuestions.checkAnswer((((JButton) (e.getSource())).getText()), thequestion)) {
				System.out.println("uh oh");
				// System.err.println("THIS IS MOST LIKELY A FALSE BUTTON CLICK. Please, check
				// if you didnt click anything yet printed this mistake message (printed on line
				// 125.)");
				// Patched by removing duplicate ActionListener on JButton
				mistakes++;
				triggerNext();
			}

			else if (screen == 3) {

			}

			else {
				String clickedOn = ((JButton) (e.getSource())).getText();

				if (clickedOn.equals("")) {
					System.err.println("JButton Text is blank!");
					System.out.println("Choices cached, printed out on line 137.");
					System.out.println("_________________");
					System.out.println(choice1);
					System.out.println(choice2);
					System.out.println(choice3);
					System.out.println(choice4);

					((JButton) (e.getSource())).setText(choice1);
					btn_choice1.setText(choice1);
					btn_choice2.setText(choice2);
					btn_choice3.setText(choice3);
					btn_choice4.setText(choice4);
					repaint();

				}
			}

		}

		else if (e.getSource() == maximumTime) {
			mistakes++;
			System.out.println("shame.");
			System.out.println(mistakes);

			if (mistakes > 4) {
				System.out.println("haha noob you failed!");
				rageaudio.start();
				screen = 3;
			}
			triggerNext();
		}

		else if (e.getSource() == playAgain && screen == 3) {
			System.out.println("Hi");
			screen = 1;
			repaint();
		}
		/*
		 * else { System.err.println("uhh no button click worked"); }
		 */

	}

	public void paintComponent(Graphics g) {
		// System.out.println("Paint");
		super.paintComponent(g);
		Graphics2D g2d = (Graphics2D) g;

		if (screen == 0) {	
			g2d.drawImage(gameTitle, 0, 0, null);
		} else if (screen == 1) {
			
			if (playAgain.isVisible()) {
				playAgain.setVisible(false);
				rageaudio.stop();
				maximumTime.stop();
			
			}
			mistakes = 0;
			points = 0;

			g2d.drawImage(gameDirections, 0, 0, null);

		}

		else if (screen == 2) {
			g2d.drawImage(gameQs, 0, 0, null);
			if (paintedButtons == false) {
				g.drawString(thequestion, 373, 50);

				// removed button code
				answerChoices = gameQuestions.returnPossibleAnswers();
				// atempted to comment this out to avoid JButton blank error, but didnt work :(
				btn_choice1.setText(answerChoices[0]);
				btn_choice1.setVisible(true);

				btn_choice2.setText(answerChoices[1]);
				btn_choice2.setVisible(true);

				btn_choice3.setText(answerChoices[2]);
				btn_choice3.setVisible(true);

				btn_choice4.setText(answerChoices[3]);
				btn_choice4.setVisible(true);

				paintedButtons = false;

				System.out.println("set buttons text to NOT blank!");

				paintedButtons = true;

				pointsDisplay.setVisible(true);
				pointsDisplay.setText(Integer.toString(points));
			}

		}

		else if (screen == 3) {
			btn_choice1.setVisible(false);
			btn_choice2.setVisible(false);
			btn_choice3.setVisible(false);
			btn_choice4.setVisible(false);

			g2d.drawImage(gameOver, 0, 0, null);
			playAgain.setVisible(true);

		}

	}

	public void setupWindow() {
		setLayout(null);

		f = new JFrame("Speedography");
		f.setSize(width, height);
		f.setLocationRelativeTo(null);
		f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		f.add(this);

		f.setVisible(true);
		f.requestFocusInWindow();

		btn_choice1 = new JButton(answerChoices[0]);
		choice1 = answerChoices[0];
		setupButton(btn_choice1, 100, 165, 430, 160, false);
		// btn_choice1.addActionListener(this);

		btn_choice2 = new JButton(answerChoices[1]);
		// choice2 = answerChoices[1];

		setupButton(btn_choice2, 525, 165, 430, 160, false);
		// btn_choice2.addActionListener(this);

		btn_choice3 = new JButton(answerChoices[2]);
		setupButton(btn_choice3, 100, 320, 430, 160, false);
		// btn_choice3.addActionListener(this);
		choice3 = answerChoices[2];

		btn_choice4 = new JButton(answerChoices[3]);
		setupButton(btn_choice4, 525, 320, 430, 160, false);
		// btn_choice4.addActionListener(this);
		choice4 = answerChoices[3];

		playAgain = new JButton("");
		playAgain.setOpaque(true);
		// method to remove border from button found @
		// https://forums.oracle.com/ords/apexds/post/removing-the-jbutton-press-effect-3292
		playAgain.setBorderPainted(true);
		playAgain.setFocusPainted(true);
		playAgain.setContentAreaFilled(false);
		playAgain.addActionListener(this);
		playAgain.setBounds(250, 315, 600, 100);
		playAgain.setVisible(false);
		add(playAgain);
		System.out.println(startButton.getX());
		add(startButton);

		pointsDisplay = new JLabel(Integer.toString(points));
		pointsDisplay.setLocation(930, 50);
		pointsDisplay.setBounds(930, 50, 50, 50);
		pointsDisplay.setVisible(false);
		add(pointsDisplay);

	}

	public void triggerNext() {
		thequestion = gameQuestions.generateQuestion();
		answerChoices = gameQuestions.returnPossibleAnswers();
		// atempted to comment this out to avoid JButton blank error, but didnt work :(
		btn_choice1.setText("");

		btn_choice2.setText("");

		btn_choice3.setText("");

		btn_choice4.setText("");

		paintedButtons = false;

		repaint();

	}

	public static void main(String[] args) {

		game thegame = new game();
		thegame.setupWindow();

	}
//	}

	public void setupButton(JButton foo, int x, int y, int width, int height, boolean focus) {
		foo.setBounds(x, y, width, height);
		foo.setVisible(false);
		foo.setBorderPainted(false);
		foo.addActionListener(this);
		foo.setContentAreaFilled(false);

		if (focus == false) {
			//foo.setFocusPainted(false);
		}

		foo.setOpaque(false);
		add(foo);
	}

	/*
	 * public void selectionHandler(JButton test) { if
	 * (gameQuestions.checkAnswer(test.getText()) == 0) { points = +1; } else {
	 * mistakes = +1; } }
	 */
	@Override
	public void mouseClicked(MouseEvent e) {
		System.out.println(e.getX());
		System.out.println(e.getY());
	}

	@Override
	public void mousePressed(MouseEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void mouseReleased(MouseEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void mouseEntered(MouseEvent e) {
		// TODO Auto-generated method stub

	}

	@Override
	public void mouseExited(MouseEvent e) {
		// TODO Auto-generated method stub

	}

}